(defun parse_puzzle_input (fp)
  (with-open-file (in fp)
    (let* ((fresh_ingredients
            (do ((l (read-line in nil) (read-line in nil))
                 (fresh_ingredients (list)))
              ((= (length l) 0) fresh_ingredients)
              (let* ((delimeter (position #\- l))
                     (sid (subseq l 0 delimeter))
                     (eid (subseq l (+ delimeter 1) (length l))))
                (push (list (parse-integer sid) (parse-integer eid)) fresh_ingredients))))
          (inventory
            (do ((l (read-line in nil) (read-line in nil))
                 (inventory (list)))
              ((null l) inventory)
              (push (parse-integer l) inventory))))
      (values fresh_ingredients inventory))))

(defun calc_fresh_ingredients (fresh inventory)
  (do ((i 0 (+ i 1))
       (fresh_items (list)))
    ((>= i (length inventory)) fresh_items)
    (let ((inventory_item (elt inventory i)))
      (do ((f 0 (+ f 1)))
        ((>= f (length fresh)))
        (destructuring-bind (from to) (elt fresh f)
          (when (and (>= inventory_item from) (<= inventory_item to))
            (push inventory_item fresh_items)
            (return)))))))

(multiple-value-bind (fresh inventory) (parse_puzzle_input "./input5.txt")
  (format t "answer part 1: ~a~%" (length (calc_fresh_ingredients fresh inventory))))
