(defun parse_input (fp)
  (with-open-file (in fp)
    (do ((l (read-line in nil) (read-line in nil))
         (problems (list)))
      ((null l) problems)
      (push (do ((i 0 (+ i 1))
                 (cell (list))
                 (cells (list)))
              ((>= i (length l)) (progn
                                   (when (> (length cell) 0) (push (concatenate 'string (reverse cell)) cells))
                                   cells))
              (let ((ch (elt l i)))
                (cond ((and (eql ch #\ ) (> (length cell) 0))
                        (push (concatenate 'string (reverse cell)) cells)
                        (setf cell (list)))
                      ((not (eql ch #\ ))
                        (push ch cell)))))
        problems))))

(let ((in (parse_input "./input6.txt"))
      (cols (list)))
  (do ((ci 0 (+ ci 1)))
    ((= ci (length (elt in 0))))
    (let ((cres 0))
      (setf cres (do ((ri 1 (+ ri 1))
                     (acc 0))
                  ((= ri (length in)) acc)
                  (let ((num (parse-integer (elt (elt in ri) ci)))
                        (op (string (elt (elt in 0) ci))))
                    (cond ((string= op #\*)
                           (when (= acc 0) (setf acc 1))
                           (setf acc (* acc num)))
                          ((string= op "+")
                           (incf acc num))))))
      (format t "~a = ~a~%" ci cres)
      (push cres cols)))
  (print (reduce #'+ cols)))
