(defun parse_input (fp)
  (with-open-file (in fp)
    (do ((l (read-line in nil) (read-line in nil))
         (problems (list)))
      ((null l) problems)
      (push (do ((i 0 (+ i 1))
                 (cell (list))
                 (cells (list)))
              ((>= i (length l)) (progn
                                   (when (> (length cell) 0) (push (concatenate 'string (reverse cell)) cells))
                                   cells))
              (let ((ch (elt l i)))
                (cond ((and (eql ch #\ ) (> (length cell) 0))
                        (push (concatenate 'string (reverse cell)) cells)
                        (setf cell (list)))
                      ((not (eql ch #\ ))
                        (push ch cell)))))
        problems))))

(let ((in (parse_input "./input6.txt"))
      (cols (list)))
  (do ((ci 0 (+ ci 1)))
    ((= ci (length (elt in 0))))
    (let ((cres 0))
      (setf cres (do ((ri 1 (+ ri 1))
                     (acc 0))
                  ((= ri (length in)) acc)
                  (let ((num (parse-integer (elt (elt in ri) ci)))
                        (op (string (elt (elt in 0) ci))))
                    (cond ((string= op #\*)
                           (when (= acc 0) (setf acc 1))
                           (setf acc (* acc num)))
                          ((string= op "+")
                           (incf acc num))))))
      (push cres cols)))
  (print (reduce #'+ cols)))

(defun resolve_part2 (fp)
  (let ((lines (list))
        (last_line nil)
        (cols_width (list))
        (answer 0))
    (with-open-file (in fp)
      (do ((l (read-line in nil) (read-line in nil)))
        ((null l) lines)
        (push l lines)))
    (setf last_line (elt lines 0))
    (do ((i 0 (+ i 1))
         (curr_el (list))
         (splitted_els (list)))
      ((= i (length last_line)) (progn (push (reverse curr_el) splitted_els)
                                       (setf cols_width (reverse splitted_els))))
      (let ((ch (elt last_line i)))
        (cond ((not (eql ch #\ ))
               (when (> (length curr_el) 0)
                     (push (reverse curr_el) splitted_els))              
               (setf curr_el (list ch)))
              (t (push ch curr_el)))))
    (do ((col_idx 0 (+ col_idx 1))
         (last_x_pos 0)
         (nums (list)))
        ((= col_idx (length cols_width)))
        (let ((col_width (length (elt cols_width col_idx))))
          (do ((x last_x_pos (+ x 1))
               (num (list)))
              ((= x (+ last_x_pos col_width)))
              (do ((y 0 (+ y 1))
                   (base 1 (* base 10)))
                  ((= y (- (length lines) 1)))
                  (let ((digit_as_char (elt (elt (reverse lines) y) x)))
                    (cond ((eql digit_as_char #\ ) nil)
                          (t (push digit_as_char num)))))
              (when (> (length num) 0)
                    (push (concatenate 'string (reverse num)) nums))
              (setf num (list)))
          (incf last_x_pos col_width))
        (let ((nums (map 'list #'parse-integer nums))
              (op (elt (elt cols_width col_idx) 0)))
          (cond ((eql op #\*) (incf answer (reduce #'* nums)))
                ((eql op #\+) (incf answer (reduce #'+ nums)))))
        (setf nums (list)))
    (print answer)))

(resolve_part2 "./input6.txt")
