(defstruct splitter x y)
(defstruct spoint x y)
(defun sum_valid_splitters (s d)
  (do ((si 0 (+ si 1))
       (vs 0))
      ((= si (length s)) (+ vs 1))
      (let ((cs (elt s si)))
        (do ((y (- (splitter-y cs) 1) (- y 1)))
          ((= y -1))
          (when (eql (at (splitter-x cs) y d) #\^)
                (return))
          (when (or (eql (at (- (splitter-x cs) 1) y d) #\^)
                    (eql (at (+ (splitter-x cs) 1) y d) #\^))
                (incf vs)
                (return))))))
(defun at (x y l)
  (elt (elt l y) x))
(let ((diagram (list))
      (splitters (list))
      (spos (make-spoint :x 0 :y 0)))
  (with-open-file
    (in "./input7.txt")
    (do ((l (read-line in nil) (read-line in nil))
         (out (list)))
        ((null l) (setf diagram (reverse out)))
        (push (coerce l 'list) out)))
  (print diagram)
  (print spos)
  (do ((y 0 (+ y 1)))
      ((= y (length diagram)))
      (do ((x 0 (+ x 1)))
          ((= x (length (elt diagram y))))
          (when (eql (at x y diagram) #\^)
                (push (make-splitter :x x :y y) splitters))
          (when (eql (at x y diagram) #\S)
                (setf (spoint-x spos) x)
                (setf (spoint-y spos) y))))
  (print splitters)
  (print spos)
  (print (sum_valid_splitters splitters diagram)))
