(defun initial_parse (fp)
  (with-open-file (in fp)
    (do* ((line (read-line in nil) (read-line in nil))
          (m (make-array 0 :fill-pointer 0 :adjustable t))
          (w (length line)))
      ((null line) (values m w (length m)))
      (vector-push-extend line m))))

(defun access (m x y)
  (elt (elt m y) x))

(defun access_or (m x y d)
  (cond ((and (>= y 0) (< y (length m)))
           (let ((row (elt m y)))
             (cond ((and (>= x 0) (< x (length row)))
                     (elt row x))
                    (t d))))
        (t d)))

(defun check_roll (m x y)
  (let ((neighbours (list (cons (- x 1) (- y 1))
                          (cons x (- y 1))
                          (cons (+ x 1) (- y 1))
                          (cons (+ x 1) y)
                          (cons (+ x 1) (+ y 1))
                          (cons x (+ y 1))
                          (cons (- x 1) (+ y 1))
                          (cons (- x 1) y))))
    (do ((i 0 (+ i 1))
         (acc 0))
      ((>= i (length neighbours)) acc)
      (let ((n (elt neighbours i)))
        (case (access_or m (car n) (cdr n) #\.)
          (#\@ (incf acc 1))
          (t ()))))))

(defun available_rolls (m w h)
  (do ((y 0 (+ y 1))
       (ar 0))
    ((>= y h) ar)
    (do ((x 0 (+ x 1)))
      ((>= x w))
      (let ((c (access m x y)))
        (when (and (eql c #\@) (< (check_roll m x y) 4))
          (incf ar))))))

(defun update_m (m x y v)
  (setf (char (elt m y) x) v))

(defun remove_available_rolls (m w h)
  (do ((y 0 (+ y 1))
       (ar 0))
    ((>= y h) ar)
    (do ((x 0 (+ x 1)))
      ((>= x w))
      (let ((c (access m x y)))
        (when (and (eql c #\@) (< (check_roll m x y) 4))
          (incf ar)
          (update_m m x y #\.))))))

(defun total_available_rolls (m w h)
  (do ((total 0) (removed_rolls -1))
    ((= removed_rolls 0) total)
    (setf removed_rolls (remove_available_rolls m w h))
    (incf total removed_rolls)))


(multiple-value-bind (m w h) (initial_parse "./input4.txt")
  (format t "part 1 answer: ~a~%" (available_rolls m w h))
  (format t "part 2 answer: ~a~%" (total_available_rolls m w h)))
